from .base import TABLE_COMMON_SUFFIX

# ═══════════════════════════════════════════════════════════════════
#  1. board_concept_index — 新浪财经-财务报表
# ═══════════════════════════════════════════════════════════════════

CREATE_FINANCIAL_BALANCE_SHEET_DDL = """
CREATE TABLE IF NOT EXISTS `financial_balance_sheet`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `report_date` DATE COMMENT '报告日',
    `current_assets` DECIMAL(20,2) COMMENT '流动资产',
    `monetary_funds` DECIMAL(20,2) COMMENT '货币资金',
    `settlement_provision` DECIMAL(20,2) COMMENT '结算备付金',
    `lent_funds` DECIMAL(20,2) COMMENT '拆出资金',
    `trading_financial_assets` DECIMAL(20,2) COMMENT '交易性金融资产',
    `buy_resale_financial_assets` DECIMAL(20,2) COMMENT '买入返售金融资产',
    `derivative_financial_assets` DECIMAL(20,2) COMMENT '衍生金融资产',
    `notes_and_accounts_receivable` DECIMAL(20,2) COMMENT '应收票据及应收账款',
    `notes_receivable` DECIMAL(20,2) COMMENT '应收票据',
    `accounts_receivable` DECIMAL(20,2) COMMENT '应收账款',
    `financing_receivables` DECIMAL(20,2) COMMENT '应收款项融资',
    `prepayments` DECIMAL(20,2) COMMENT '预付款项',
    `dividends_receivable` DECIMAL(20,2) COMMENT '应收股利',
    `interest_receivable` DECIMAL(20,2) COMMENT '应收利息',
    `premiums_receivable` DECIMAL(20,2) COMMENT '应收保费',
    `reinsurance_receivable` DECIMAL(20,2) COMMENT '应收分保账款',
    `reinsurance_contract_reserve_receivable` DECIMAL(20,2) COMMENT '应收分保合同准备金',
    `export_tax_rebate_receivable` DECIMAL(20,2) COMMENT '应收出口退税',
    `subsidy_receivable` DECIMAL(20,2) COMMENT '应收补贴款',
    `margin_receivable` DECIMAL(20,2) COMMENT '应收保证金',
    `internal_receivable` DECIMAL(20,2) COMMENT '内部应收款',
    `other_receivables` DECIMAL(20,2) COMMENT '其他应收款',
    `other_receivables_total` DECIMAL(20,2) COMMENT '其他应收款(合计)',
    `inventories` DECIMAL(20,2) COMMENT '存货',
    `assets_held_for_sale` DECIMAL(20,2) COMMENT '划分为持有待售的资产',
    `deferred_expenses` DECIMAL(20,2) COMMENT '待摊费用',
    `pending_disposal_current_asset_loss` DECIMAL(20,2) COMMENT '待处理流动资产损益',
    `non_current_assets_due_within_one_year` DECIMAL(20,2) COMMENT '一年内到期的非流动资产',
    `other_current_assets` DECIMAL(20,2) COMMENT '其他流动资产',
    `total_current_assets` DECIMAL(20,2) COMMENT '流动资产合计',
    `non_current_assets` DECIMAL(20,2) COMMENT '非流动资产',
    `loans_and_advances_to_customers` DECIMAL(20,2) COMMENT '发放贷款及垫款',
    `debt_investments` DECIMAL(20,2) COMMENT '债权投资',
    `other_debt_investments` DECIMAL(20,2) COMMENT '其他债权投资',
    `fvoci_financial_assets` DECIMAL(20,2) COMMENT '以公允价值计量且其变动计入其他综合收益的金融资产',
    `amortized_cost_financial_assets` DECIMAL(20,2) COMMENT '以摊余成本计量的金融资产',
    `available_for_sale_financial_assets` DECIMAL(20,2) COMMENT '可供出售金融资产',
    `long_term_equity_investments` DECIMAL(20,2) COMMENT '长期股权投资',
    `investment_properties` DECIMAL(20,2) COMMENT '投资性房地产',
    `long_term_receivables` DECIMAL(20,2) COMMENT '长期应收款',
    `other_equity_instruments` DECIMAL(20,2) COMMENT '其他权益工具投资',
    `other_non_current_financial_assets` DECIMAL(20,2) COMMENT '其他非流动金融资产',
    `other_long_term_investments` DECIMAL(20,2) COMMENT '其他长期投资',
    `fixed_assets_original_cost` DECIMAL(20,2) COMMENT '固定资产原值',
    `accumulated_depreciation` DECIMAL(20,2) COMMENT '累计折旧',
    `fixed_assets_net_book_value` DECIMAL(20,2) COMMENT '固定资产净值',
    `fixed_assets_impairment` DECIMAL(20,2) COMMENT '固定资产减值准备',
    `construction_in_progress_total` DECIMAL(20,2) COMMENT '在建工程合计',
    `construction_in_progress` DECIMAL(20,2) COMMENT '在建工程',
    `engineering_materials` DECIMAL(20,2) COMMENT '工程物资',
    `fixed_assets_net_amount` DECIMAL(20,2) COMMENT '固定资产净额',
    `fixed_assets_clearance` DECIMAL(20,2) COMMENT '固定资产清理',
    `fixed_assets_and_clearance_total` DECIMAL(20,2) COMMENT '固定资产及清理合计',
    `productive_biological_assets` DECIMAL(20,2) COMMENT '生产性生物资产',
    `public_welfare_biological_assets` DECIMAL(20,2) COMMENT '公益性生物资产',
    `oil_and_gas_assets` DECIMAL(20,2) COMMENT '油气资产',
    `contract_assets` DECIMAL(20,2) COMMENT '合同资产',
    `right_of_use_assets` DECIMAL(20,2) COMMENT '使用权资产',
    `intangible_assets` DECIMAL(20,2) COMMENT '无形资产',
    `development_costs` DECIMAL(20,2) COMMENT '开发支出',
    `goodwill` DECIMAL(20,2) COMMENT '商誉',
    `long_term_prepaid_expenses` DECIMAL(20,2) COMMENT '长期待摊费用',
    `equity_split_circulation_rights` DECIMAL(20,2) COMMENT '股权分置流通权',
    `deferred_tax_assets` DECIMAL(20,2) COMMENT '递延所得税资产',
    `other_non_current_assets` DECIMAL(20,2) COMMENT '其他非流动资产',
    `total_non_current_assets` DECIMAL(20,2) COMMENT '非流动资产合计',
    `total_assets` DECIMAL(20,2) COMMENT '资产总计',
    `current_liabilities` DECIMAL(20,2) COMMENT '流动负债',
    `short_term_borrowings` DECIMAL(20,2) COMMENT '短期借款',
    `borrowings_from_central_bank` DECIMAL(20,2) COMMENT '向中央银行借款',
    `deposits_and_interbank_deposits` DECIMAL(20,2) COMMENT '吸收存款及同业存放',
    `interbank_borrowings` DECIMAL(20,2) COMMENT '拆入资金',
    `trading_financial_liabilities` DECIMAL(20,2) COMMENT '交易性金融负债',
    `derivative_financial_liabilities` DECIMAL(20,2) COMMENT '衍生金融负债',
    `notes_and_accounts_payable` DECIMAL(20,2) COMMENT '应付票据及应付账款',
    `notes_payable` DECIMAL(20,2) COMMENT '应付票据',
    `accounts_payable` DECIMAL(20,2) COMMENT '应付账款',
    `advances_from_customers` DECIMAL(20,2) COMMENT '预收款项',
    `contract_liabilities` DECIMAL(20,2) COMMENT '合同负债',
    `repurchase_of_financial_assets_sold` DECIMAL(20,2) COMMENT '卖出回购金融资产款',
    `fees_and_commissions_payable` DECIMAL(20,2) COMMENT '应付手续费及佣金',
    `employee_benefits_payable` DECIMAL(20,2) COMMENT '应付职工薪酬',
    `taxes_and_surcharges_payable` DECIMAL(20,2) COMMENT '应交税费',
    `interest_payable` DECIMAL(20,2) COMMENT '应付利息',
    `dividends_payable` DECIMAL(20,2) COMMENT '应付股利',
    `margin_payable` DECIMAL(20,2) COMMENT '应付保证金',
    `internal_payable` DECIMAL(20,2) COMMENT '内部应付款',
    `other_payables` DECIMAL(20,2) COMMENT '其他应付款',
    `other_payables_total` DECIMAL(20,2) COMMENT '其他应付款合计',
    `other_levies_payable` DECIMAL(20,2) COMMENT '其他应交款',
    `guarantee_liability_reserve` DECIMAL(20,2) COMMENT '担保责任赔偿准备金',
    `reinsurance_payable` DECIMAL(20,2) COMMENT '应付分保账款',
    `insurance_contract_reserves` DECIMAL(20,2) COMMENT '保险合同准备金',
    `securities_trading_agency_funds` DECIMAL(20,2) COMMENT '代理买卖证券款',
    `underwriting_agency_funds` DECIMAL(20,2) COMMENT '代理承销证券款',
    `international_bill_settlement` DECIMAL(20,2) COMMENT '国际票证结算',
    `domestic_bill_settlement` DECIMAL(20,2) COMMENT '国内票证结算',
    `accrued_expenses` DECIMAL(20,2) COMMENT '预提费用',
    `estimated_current_liabilities` DECIMAL(20,2) COMMENT '预计流动负债',
    `short_term_bonds_payable` DECIMAL(20,2) COMMENT '应付短期债券',
    `liabilities_held_for_sale` DECIMAL(20,2) COMMENT '划分为持有待售的负债',
    `deferred_income_due_within_one_year` DECIMAL(20,2) COMMENT '一年内的递延收益',
    `non_current_liabilities_due_within_one_year` DECIMAL(20,2) COMMENT '一年内到期的非流动负债',
    `other_current_liabilities` DECIMAL(20,2) COMMENT '其他流动负债',
    `total_current_liabilities` DECIMAL(20,2) COMMENT '流动负债合计',
    `non_current_liabilities` DECIMAL(20,2) COMMENT '非流动负债',
    `long_term_borrowings` DECIMAL(20,2) COMMENT '长期借款',
    `bonds_payable` DECIMAL(20,2) COMMENT '应付债券',
    `preferred_stock_payable` DECIMAL(20,2) COMMENT '应付债券：优先股',
    `perpetual_bonds_payable` DECIMAL(20,2) COMMENT '应付债券：永续债',
    `lease_liabilities` DECIMAL(20,2) COMMENT '租赁负债',
    `long_term_employee_benefits_payable` DECIMAL(20,2) COMMENT '长期应付职工薪酬',
    `long_term_accounts_payable` DECIMAL(20,2) COMMENT '长期应付款',
    `long_term_payables_total` DECIMAL(20,2) COMMENT '长期应付款合计',
    `special_payables` DECIMAL(20,2) COMMENT '专项应付款',
    `estimated_non_current_liabilities` DECIMAL(20,2) COMMENT '预计非流动负债',
    `long_term_deferred_income` DECIMAL(20,2) COMMENT '长期递延收益',
    `deferred_tax_liabilities` DECIMAL(20,2) COMMENT '递延所得税负债',
    `other_non_current_liabilities` DECIMAL(20,2) COMMENT '其他非流动负债',
    `total_non_current_liabilities` DECIMAL(20,2) COMMENT '非流动负债合计',
    `total_liabilities` DECIMAL(20,2) COMMENT '负债合计',
    `owners_equity` DECIMAL(20,2) COMMENT '所有者权益',
    `paid_in_capital` DECIMAL(20,2) COMMENT '实收资本(或股本)',
    `other_equity_instruments_total` DECIMAL(20,2) COMMENT '其他权益工具',
    `preferred_stock` DECIMAL(20,2) COMMENT '优先股',
    `perpetual_bonds` DECIMAL(20,2) COMMENT '永续债',
    `capital_reserve` DECIMAL(20,2) COMMENT '资本公积',
    `treasury_stock` DECIMAL(20,2) COMMENT '减:库存股',
    `other_comprehensive_income` DECIMAL(20,2) COMMENT '其他综合收益',
    `specific_reserve` DECIMAL(20,2) COMMENT '专项储备',
    `surplus_reserve` DECIMAL(20,2) COMMENT '盈余公积',
    `general_risk_reserve` DECIMAL(20,2) COMMENT '一般风险准备',
    `unrecognized_investment_loss` DECIMAL(20,2) COMMENT '未确定的投资损失',
    `retained_earnings` DECIMAL(20,2) COMMENT '未分配利润',
    `proposed_cash_dividends` DECIMAL(20,2) COMMENT '拟分配现金股利',
    `foreign_currency_translation_difference` DECIMAL(20,2) COMMENT '外币报表折算差额',
    `total_equity_attributable_to_parent` DECIMAL(20,2) COMMENT '归属于母公司股东权益合计',
    `minority_interests` DECIMAL(20,2) COMMENT '少数股东权益',
    `total_owners_equity` DECIMAL(20,2) COMMENT '所有者权益(或股东权益)合计',
    `total_liabilities_and_equity` DECIMAL(20,2) COMMENT '负债和所有者权益(或股东权益)总计',
    `data_source` VARCHAR(50) COMMENT '数据源',
    `is_audited` VARCHAR(10) COMMENT '是否审计',
    `announcement_date` DATE COMMENT '公告日期',
    `currency` CHAR(3) COMMENT '币种',
    `statement_type` VARCHAR(50) COMMENT '类型 (如合并期末)',

    PRIMARY KEY (`id`),
    INDEX `idx_report_date` (`report_date`),
    INDEX `idx_currency` (`currency`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='资产负债表')


# 利润表
CREATE_FINANCIAL_INCOME_STATEMENT_DDL = """
CREATE TABLE IF NOT EXISTS `financial_income_statement`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `report_date` DATE COMMENT '报告日',
    `operating_revenue` DECIMAL(20,2) COMMENT '营业总收入',
    `revenue` DECIMAL(20,2) COMMENT '营业收入',
    `interest_income` DECIMAL(20,2) COMMENT '利息收入',
    `earned_premium` DECIMAL(20,2) COMMENT '已赚保费',
    `fee_and_commission_income` DECIMAL(20,2) COMMENT '手续费及佣金收入',
    `real_estate_sales_income` DECIMAL(20,2) COMMENT '房地产销售收入',
    `other_business_income` DECIMAL(20,2) COMMENT '其他业务收入',
    `operating_cost_total` DECIMAL(20,2) COMMENT '营业总成本',
    `operating_cost` DECIMAL(20,2) COMMENT '营业成本',
    `fee_and_commission_expense` DECIMAL(20,2) COMMENT '手续费及佣金支出',
    `real_estate_sales_cost` DECIMAL(20,2) COMMENT '房地产销售成本',
    `surrender_refund` DECIMAL(20,2) COMMENT '退保金',
    `net_claim_payout` DECIMAL(20,2) COMMENT '赔付支出净额',
    `net_insurance_contract_reserve_withdrawal` DECIMAL(20,2) COMMENT '提取保险合同准备金净额',
    `policy_dividend_expense` DECIMAL(20,2) COMMENT '保单红利支出',
    `reinsurance_expense` DECIMAL(20,2) COMMENT '分保费用',
    `other_business_cost` DECIMAL(20,2) COMMENT '其他业务成本',
    `taxes_and_surcharges` DECIMAL(20,2) COMMENT '营业税金及附加',
    `rd_expense` DECIMAL(20,2) COMMENT '研发费用',
    `sales_expense` DECIMAL(20,2) COMMENT '销售费用',
    `admin_expense` DECIMAL(20,2) COMMENT '管理费用',
    `finance_expense` DECIMAL(20,2) COMMENT '财务费用',
    `interest_expense` DECIMAL(20,2) COMMENT '利息费用',
    `interest_paid` DECIMAL(20,2) COMMENT '利息支出',
    `investment_income` DECIMAL(20,2) COMMENT '投资收益',
    `investment_income_from_associates` DECIMAL(20,2) COMMENT '对联营企业和合营企业的投资收益',
    `gain_from_amortized_cost_financial_assets_termination` DECIMAL(20,2) COMMENT '以摊余成本计量的金融资产终止确认产生的收益',
    `exchange_gain` DECIMAL(20,2) COMMENT '汇兑收益',
    `net_hedging_income` DECIMAL(20,2) COMMENT '净敞口套期收益',
    `fair_value_change_gain` DECIMAL(20,2) COMMENT '公允价值变动收益',
    `futures_gain_loss` DECIMAL(20,2) COMMENT '期货损益',
    `custody_income` DECIMAL(20,2) COMMENT '托管收益',
    `subsidy_income` DECIMAL(20,2) COMMENT '补贴收入',
    `other_gains` DECIMAL(20,2) COMMENT '其他收益',
    `asset_impairment_loss` DECIMAL(20,2) COMMENT '资产减值损失',
    `credit_impairment_loss` DECIMAL(20,2) COMMENT '信用减值损失',
    `other_business_profit` DECIMAL(20,2) COMMENT '其他业务利润',
    `asset_disposal_gain` DECIMAL(20,2) COMMENT '资产处置收益',
    `operating_profit` DECIMAL(20,2) COMMENT '营业利润',
    `non_operating_income` DECIMAL(20,2) COMMENT '营业外收入',
    `gain_on_disposal_of_non_current_assets` DECIMAL(20,2) COMMENT '非流动资产处置利得',
    `non_operating_expense` DECIMAL(20,2) COMMENT '营业外支出',
    `loss_on_disposal_of_non_current_assets` DECIMAL(20,2) COMMENT '非流动资产处置损失',
    `profit_before_tax` DECIMAL(20,2) COMMENT '利润总额',
    `income_tax_expense` DECIMAL(20,2) COMMENT '所得税费用',
    `unrecognized_investment_loss` DECIMAL(20,2) COMMENT '未确认投资损失',
    `net_profit` DECIMAL(20,2) COMMENT '净利润',
    `net_profit_continuing_operations` DECIMAL(20,2) COMMENT '持续经营净利润',
    `net_profit_discontinued_operations` DECIMAL(20,2) COMMENT '终止经营净利润',
    `net_profit_parent_owners` DECIMAL(20,2) COMMENT '归属于母公司所有者的净利润',
    `net_profit_acquiree_before_combination` DECIMAL(20,2) COMMENT '被合并方在合并前实现净利润',
    `minority_profit_share` DECIMAL(20,2) COMMENT '少数股东损益',
    `other_comprehensive_income` DECIMAL(20,2) COMMENT '其他综合收益',
    `parent_other_comprehensive_income` DECIMAL(20,2) COMMENT '归属于母公司所有者的其他综合收益',
    `oci_not_reclassified_to_pl` DECIMAL(20,2) COMMENT '（一）以后不能重分类进损益的其他综合收益',
    `remeasurement_of_defined_benefit_plan` DECIMAL(20,2) COMMENT '重新计量设定受益计划变动额',
    `oci_equity_method_not_reclassified` DECIMAL(20,2) COMMENT '权益法下不能转损益的其他综合收益',
    `fvoci_equity_instruments` DECIMAL(20,2) COMMENT '其他权益工具投资公允价值变动',
    `credit_risk_fair_value_change` DECIMAL(20,2) COMMENT '企业自身信用风险公允价值变动',
    `oci_will_be_reclassified_to_pl` DECIMAL(20,2) COMMENT '（二）以后将重分类进损益的其他综合收益',
    `equity_method_oci_reclassified` DECIMAL(20,2) COMMENT '权益法下可转损益的其他综合收益',
    `available_for_sale_fv_change` DECIMAL(20,2) COMMENT '可供出售金融资产公允价值变动损益',
    `other_debt_investments_fv_change` DECIMAL(20,2) COMMENT '其他债权投资公允价值变动',
    `reclassified_from_fvoci_to_pl` DECIMAL(20,2) COMMENT '金融资产重分类计入其他综合收益的金额',
    `other_debt_investments_credit_impairment` DECIMAL(20,2) COMMENT '其他债权投资信用减值准备',
    `reclassified_from_htm_to_afs` DECIMAL(20,2) COMMENT '持有至到期投资重分类为可供出售金融资产损益',
    `cash_flow_hedge_reserve` DECIMAL(20,2) COMMENT '现金流量套期储备',
    `effective_cash_flow_hedge` DECIMAL(20,2) COMMENT '现金流量套期损益的有效部分',
    `foreign_currency_translation_reserve` DECIMAL(20,2) COMMENT '外币财务报表折算差额',
    `other_oci` DECIMAL(20,2) COMMENT '其他',
    `minority_other_comprehensive_income` DECIMAL(20,2) COMMENT '归属于少数股东的其他综合收益',
    `total_comprehensive_income` DECIMAL(20,2) COMMENT '综合收益总额',
    `parent_total_comprehensive_income` DECIMAL(20,2) COMMENT '归属于母公司所有者的综合收益总额',
    `minority_total_comprehensive_income` DECIMAL(20,2) COMMENT '归属于少数股东的综合收益总额',
    `basic_eps` DECIMAL(20,6) COMMENT '基本每股收益',
    `diluted_eps` DECIMAL(20,6) COMMENT '稀释每股收益',
    `data_source` VARCHAR(50) COMMENT '数据源',
    `is_audited` VARCHAR(10) COMMENT '是否审计',
    `announcement_date` DATE COMMENT '公告日期',
    `currency` CHAR(3) COMMENT '币种',
    `statement_type` VARCHAR(50) COMMENT '类型',
   
    PRIMARY KEY (`id`),
    INDEX `idx_report_date` (`report_date`),
    INDEX `idx_currency` (`currency`),
    INDEX `idx_data_source` (`data_source`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='利润表(基于东方财富财报数据)')

# 现金流量表
CREATE_FINANCIAL_CASH_FLOW_DDL = """
CREATE TABLE IF NOT EXISTS `financial_cash_flow_statement`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `report_date` DATE COMMENT '报告日',
    `operating_cash_flow` DECIMAL(20,2) COMMENT '经营活动产生的现金流量',
    `cash_received_from_sales` DECIMAL(20,2) COMMENT '销售商品、提供劳务收到的现金',
    `net_increase_deposits_interbank` DECIMAL(20,2) COMMENT '客户存款和同业存放款项净增加额',
    `net_increase_central_bank_borrowings` DECIMAL(20,2) COMMENT '向中央银行借款净增加额',
    `net_increase_interbank_borrowings` DECIMAL(20,2) COMMENT '向其他金融机构拆入资金净增加额',
    `cash_received_from_insurance_premiums` DECIMAL(20,2) COMMENT '收到原保险合同保费取得的现金',
    `net_cash_received_from_reinsurance` DECIMAL(20,2) COMMENT '收到再保险业务现金净额',
    `net_increase_policyholder_funds` DECIMAL(20,2) COMMENT '保户储金及投资款净增加额',
    `net_increase_trading_financial_assets_disposal` DECIMAL(20,2) COMMENT '处置交易性金融资产净增加额',
    `cash_received_from_fees_and_commissions` DECIMAL(20,2) COMMENT '收取利息、手续费及佣金的现金',
    `net_increase_borrowed_funds` DECIMAL(20,2) COMMENT '拆入资金净增加额',
    `net_increase_repurchase_funds` DECIMAL(20,2) COMMENT '回购业务资金净增加额',
    `tax_refund_received` DECIMAL(20,2) COMMENT '收到的税费返还',
    `other_cash_received_operating` DECIMAL(20,2) COMMENT '收到的其他与经营活动有关的现金',
    `subtotal_cash_inflows_operating` DECIMAL(20,2) COMMENT '经营活动现金流入小计',
    `cash_paid_for_goods_and_services` DECIMAL(20,2) COMMENT '购买商品、接受劳务支付的现金',
    `net_increase_loans_and_advances` DECIMAL(20,2) COMMENT '客户贷款及垫款净增加额',
    `net_increase_deposits_central_bank` DECIMAL(20,2) COMMENT '存放中央银行和同业款项净增加额',
    `cash_paid_for_insurance_claims` DECIMAL(20,2) COMMENT '支付原保险合同赔付款项的现金',
    `cash_paid_for_fees_and_commissions` DECIMAL(20,2) COMMENT '支付利息、手续费及佣金的现金',
    `cash_paid_for_policy_dividends` DECIMAL(20,2) COMMENT '支付保单红利的现金',
    `cash_paid_to_employees` DECIMAL(20,2) COMMENT '支付给职工以及为职工支付的现金',
    `cash_paid_for_taxes` DECIMAL(20,2) COMMENT '支付的各项税费',
    `other_cash_paid_operating` DECIMAL(20,2) COMMENT '支付的其他与经营活动有关的现金',
    `subtotal_cash_outflows_operating` DECIMAL(20,2) COMMENT '经营活动现金流出小计',
    `net_cash_flow_operating` DECIMAL(20,2) COMMENT '经营活动产生的现金流量净额',
    `investing_cash_flow` DECIMAL(20,2) COMMENT '投资活动产生的现金流量',
    `cash_received_from_disposal_investments` DECIMAL(20,2) COMMENT '收回投资所收到的现金',
    `cash_received_from_investment_income` DECIMAL(20,2) COMMENT '取得投资收益收到的现金',
    `cash_received_from_disposal_fixed_assets` DECIMAL(20,2) COMMENT '处置固定资产、无形资产和其他长期资产所收回的现金净额',
    `cash_received_from_disposal_subsidiaries` DECIMAL(20,2) COMMENT '处置子公司及其他营业单位收到的现金净额',
    `other_cash_received_investing` DECIMAL(20,2) COMMENT '收到的其他与投资活动有关的现金',
    `cash_received_from_reduction_pledged_deposits` DECIMAL(20,2) COMMENT '减少质押和定期存款所收到的现金',
    `cash_received_from_disposal_afs` DECIMAL(20,2) COMMENT '处置可供出售金融资产净增加额',
    `subtotal_cash_inflows_investing` DECIMAL(20,2) COMMENT '投资活动现金流入小计',
    `cash_paid_for_acquisition_fixed_assets` DECIMAL(20,2) COMMENT '购建固定资产、无形资产和其他长期资产所支付的现金',
    `cash_paid_for_investments` DECIMAL(20,2) COMMENT '投资所支付的现金',
    `net_increase_pledged_loans` DECIMAL(20,2) COMMENT '质押贷款净增加额',
    `cash_paid_for_acquisition_subsidiaries` DECIMAL(20,2) COMMENT '取得子公司及其他营业单位支付的现金净额',
    `cash_paid_for_increase_pledged_deposits` DECIMAL(20,2) COMMENT '增加质押和定期存款所支付的现金',
    `other_cash_paid_investing` DECIMAL(20,2) COMMENT '支付的其他与投资活动有关的现金',
    `subtotal_cash_outflows_investing` DECIMAL(20,2) COMMENT '投资活动现金流出小计',
    `net_cash_flow_investing` DECIMAL(20,2) COMMENT '投资活动产生的现金流量净额',
    `financing_cash_flow` DECIMAL(20,2) COMMENT '筹资活动产生的现金流量',
    `cash_received_from_equity_investments` DECIMAL(20,2) COMMENT '吸收投资收到的现金',
    `cash_received_from_minority_equity` DECIMAL(20,2) COMMENT '子公司吸收少数股东投资收到的现金',
    `cash_received_from_borrowings` DECIMAL(20,2) COMMENT '取得借款收到的现金',
    `cash_received_from_bond_issuance` DECIMAL(20,2) COMMENT '发行债券收到的现金',
    `other_cash_received_financing` DECIMAL(20,2) COMMENT '收到其他与筹资活动有关的现金',
    `subtotal_cash_inflows_financing` DECIMAL(20,2) COMMENT '筹资活动现金流入小计',
    `cash_paid_for_debt_repayment` DECIMAL(20,2) COMMENT '偿还债务支付的现金',
    `cash_paid_for_dividends_interest` DECIMAL(20,2) COMMENT '分配股利、利润或偿付利息所支付的现金',
    `cash_paid_to_minority_shareholders` DECIMAL(20,2) COMMENT '子公司支付给少数股东的股利、利润',
    `other_cash_paid_financing` DECIMAL(20,2) COMMENT '支付其他与筹资活动有关的现金',
    `subtotal_cash_outflows_financing` DECIMAL(20,2) COMMENT '筹资活动现金流出小计',
    `net_cash_flow_financing` DECIMAL(20,2) COMMENT '筹资活动产生的现金流量净额',
    `effect_of_exchange_rate_changes` DECIMAL(20,2) COMMENT '汇率变动对现金及现金等价物的影响',
    `net_increase_cash_equivalents` DECIMAL(20,2) COMMENT '现金及现金等价物净增加额',
    `beginning_cash_equivalents` DECIMAL(20,2) COMMENT '期初现金及现金等价物余额',
    `ending_cash` DECIMAL(20,2) COMMENT '现金的期末余额',
    `beginning_cash` DECIMAL(20,2) COMMENT '现金的期初余额',
    `ending_cash_equivalents` DECIMAL(20,2) COMMENT '现金等价物的期末余额',
    `cash_equivalents` DECIMAL(20,2) COMMENT '现金等价物的期初余额',
    `ending_cash_and_equivalents` DECIMAL(20,2) COMMENT '期末现金及现金等价物余额',
    `data_source` VARCHAR(50) COMMENT '数据源',
    `is_audited` VARCHAR(10) COMMENT '是否审计',
    `announcement_date` DATE COMMENT '公告日期',
    `currency` CHAR(3) COMMENT '币种',
    `statement_type` VARCHAR(50) COMMENT '类型',
  
    PRIMARY KEY (`id`),
    INDEX `idx_report_date` (`report_date`),
    INDEX `idx_currency` (`currency`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='现金流量表(基于东方财富财报数据)')


CREATE_FINANCIAL_FORECAST_SUMMARY_DDL = """
CREATE TABLE IF NOT EXISTS `financial_forecast_summary`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `symbol` VARCHAR(10) NOT NULL COMMENT '股票代码',
    `name` VARCHAR(10) DEFAULT NULL COMMENT '股票代码',
    `forecast_type` VARCHAR(20) NOT NULL COMMENT '预测数据类型',
    `forecast_year` YEAR NOT NULL COMMENT '预测年度',
    `institution_count` INT UNSIGNED COMMENT '预测机构数',
    `forecast_min` DECIMAL(20,4) COMMENT '预测最小值',
    `forecast_mean` DECIMAL(20,4) COMMENT '预测均值',
    `forecast_max` DECIMAL(20,4) COMMENT '预测最大值',
    `industry_average` DECIMAL(20,4) COMMENT '行业平均数',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_stock_year` (`symbol`, `name`, `forecast_year`, `forecast_type`),
    INDEX `idx_forecast_year` (`forecast_year`),
    INDEX `idx_symbol` (`symbol`),
    INDEX `idx_name` (`name`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='财务预测汇总表(东财)')

# 业绩预测详表-机构
CREATE_FINANCIAL_FORECAST_INSTITUTION_DDL = """
CREATE TABLE IF NOT EXISTS `financial_forecast_institution_detail`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `symbol` VARCHAR(10) NOT NULL COMMENT '股票代码',
    `name` VARCHAR(10) DEFAULT NULL COMMENT '股票名称',
    `institution_name` VARCHAR(200) COMMENT '机构名称',
    `researcher` VARCHAR(100) COMMENT '研究员',
    `forecast_eps_2026` DECIMAL(20,4) COMMENT '预测年报每股收益2026预测',
    `forecast_eps_2027` DECIMAL(20,4) COMMENT '预测年报每股收益2027预测',
    `forecast_eps_2028` DECIMAL(20,4) COMMENT '预测年报每股收益2028预测',
    `forecast_net_profit_2026` DECIMAL(20,4) COMMENT '预测年报净利润2026预测（单位：百万元或亿元，需确认）',
    `forecast_net_profit_2027` DECIMAL(20,4) COMMENT '预测年报净利润2027预测',
    `forecast_net_profit_2028` DECIMAL(20,4) COMMENT '预测年报净利润2028预测',
    `report_date` DATE COMMENT '报告日期',
    `data_source` VARCHAR(50) DEFAULT '同花顺' COMMENT '数据来源',
  
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_stock_inst_report` (`symbol`, `institution_name`, `report_date`, `researcher`),
    KEY `idx_symbol` (`symbol`),
    KEY `idx_report_date` (`report_date`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='业绩预测详表-机构')


# 业绩预测详表-详细指标预测
CREATE_FINANCIAL_INDICATOR_TREND_DDL = """
CREATE TABLE IF NOT EXISTS `financial_indicator_trend`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `symbol` VARCHAR(10) NOT NULL COMMENT '股票代码',
    `name` VARCHAR(10) DEFAULT NULL COMMENT '股票名称',
    `indicator` VARCHAR(100) NOT NULL COMMENT '预测指标（如营业收入(元)、净利润等）',
    `actual_2023` DECIMAL(20,2) COMMENT '2023年实际值（单位：元）',
    `actual_2024` DECIMAL(20,2) COMMENT '2024年实际值（单位：元）',
    `actual_2025` DECIMAL(20,2) COMMENT '2025年实际值（单位：元）',
    `forecast_2026_avg` DECIMAL(20,2) COMMENT '2026年预测平均值（单位：元）',
    `forecast_2027_avg` DECIMAL(20,2) COMMENT '2027年预测平均值（单位：元）',
    `forecast_2028_avg` DECIMAL(20,2) COMMENT '2028年预测平均值（单位：元）',
    `data_source` VARCHAR(50) DEFAULT '同花顺' COMMENT '数据来源',
    
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_stock_indicator` (`symbol`, `indicator`, `name`),
    KEY `idx_symbol` (`symbol`),
    KEY `idx_name` (`name`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='业绩预测详表-详细指标预测')


# 资金流向-个股资金流
CREATE_STOCK_FUNDS_DDL = """
CREATE TABLE IF NOT EXISTS `stock_funds_flow`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `symbol` VARCHAR(10) NOT NULL COMMENT '股票代码',
    `name` VARCHAR(50) NOT NULL COMMENT '股票简称',
    `period_type` VARCHAR(50) NOT NULL COMMENT '周期类型',
    `stat_date` DATE NOT NULL COMMENT '数据日期',
    `latest_price` DECIMAL(10,3) COMMENT '最新价',
    `change_percent` DECIMAL(10,4) COMMENT '涨跌幅（%）',
    `phase_change` DECIMAL(10,4) COMMENT '阶段涨跌幅',
    `turnover_rate` DECIMAL(10,4) COMMENT '换手率（%）',
    `inflow_amount` DECIMAL(20,2) COMMENT '流入资金（元）',
    `outflow_amount` DECIMAL(20,2) COMMENT '流出资金（元）',
    `net_amount` DECIMAL(20,2) COMMENT '净额（元）',
    `turnover_amount` DECIMAL(20,2) COMMENT '成交额（元）',
    `serial_number` SMALLINT UNSIGNED COMMENT '排名',
    
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_symbol_period_date` (`symbol`, `period_type`, `stat_date`),
    KEY `idx_period_date_serial_number` (`period_type`, `stat_date`, `serial_number`),
    KEY `idx_symbol` (`symbol`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='资金流向-个股资金流')

# 资金流向-概念资金流
CREATE_INDUSTRY_FUNDS_INDIVIDUAL_DDL = """
CREATE TABLE IF NOT EXISTS `industry_funds_flow_individual`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `serial_number` INT NOT NULL COMMENT '序号',
    `industry` VARCHAR(50) NOT NULL COMMENT '行业',
    `period_type` VARCHAR(50) NOT NULL COMMENT '周期类型',
    `stat_date` DATE NOT NULL COMMENT '数据日期',
    `index_price` DECIMAL(10,2) NOT NULL COMMENT '行业指数',
    `change_ratio` DECIMAL(10,2) DEFAULT NULL COMMENT '行业-涨跌幅(%)',
    `inflow_amount` DECIMAL(20,2) DEFAULT NULL COMMENT '流入资金',
    `outflow_amount` DECIMAL(20,2) DEFAULT NULL COMMENT '流出资金',
    `net_amount` DECIMAL(20,2) DEFAULT NULL COMMENT '净额',
    `company_count` INT NOT NULL COMMENT '公司家数',
    `leading_stock_name` VARCHAR(50) DEFAULT NULL COMMENT '领涨股',
    `leading_stock_change` DECIMAL(10,2) DEFAULT NULL COMMENT '领涨股-涨跌幅(%)',
    `current_price` DECIMAL(10,2) DEFAULT NULL COMMENT '当前价',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_industry_serial_no` (`industry`, `serial_number`, `stat_date`, `period_type`),
    KEY `idx_serial_no` (`serial_number`),
    KEY `idx_stat_date` (`stat_date`),
    KEY `idx_industry` (`industry`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='资金流向-行业资金流')


# 东方财富-数据中心-个股资金流向
CREATE_STOCK_INDIVIDUAL_FUND_FLOW_DDL= """
CREATE TABLE IF NOT EXISTS `stock_individual_fund_flow`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `symbol` VARCHAR(10) NOT NULL COMMENT '股票代码',
    `name` VARCHAR(40) DEFAULT NULL COMMENT '股票名称',
    `trade_date` DATE NOT NULL COMMENT '交易日期',
    `close_price` DECIMAL(10,3) DEFAULT NULL COMMENT '收盘价',
    `change_percent` DECIMAL(8,3) DEFAULT NULL COMMENT '涨跌幅（单位：%）',
    `main_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '主力净流入-净额',
    `main_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '主力净流入-净占比（单位：%）',
    `super_large_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '超大单净流入-净额',
    `super_large_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '超大单净流入-净占比（单位：%）',
    `large_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '大单净流入-净额',
    `large_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '大单净流入-净占比（单位：%）',
    `medium_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '中单净流入-净额',
    `medium_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '中单净流入-净占比（单位：%）',
    `small_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '小单净流入-净额',
    `small_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '小单净流入-净占比（单位：%）',
    
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_symbol_date` (`symbol`, `trade_date`),
    KEY `idx_symbol` (`symbol`),
    KEY `idx_trade_date` (`trade_date`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='个股资金流向')

# 东方财富-数据中心-个股资金流向
CREATE_STOCK_RANK_FUND_FLOW_DDL = """
CREATE TABLE IF NOT EXISTS `stock_rank_fund_flow`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `serial_number` INT NOT NULL COMMENT '序号（排名）',
    `symbol` VARCHAR(10) NOT NULL COMMENT '股票代码',
    `name` VARCHAR(50) NOT NULL COMMENT '股票名称',
    `latest_price` DECIMAL(10,3) DEFAULT NULL COMMENT '最新价',
    `pct_change_today` DECIMAL(8,3) DEFAULT NULL COMMENT '今日涨跌幅（单位：%）',
    `main_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '今日主力净流入-净额',
    `main_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '今日主力净流入-净占比（单位：%）',
    `super_large_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '今日超大单净流入-净额',
    `super_large_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '今日超大单净流入-净占比（单位：%）',
    `large_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '今日大单净流入-净额',
    `large_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '今日大单净流入-净占比（单位：%）',
    `medium_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '今日中单净流入-净额',
    `medium_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '今日中单净流入-净占比（单位：%）',
    `small_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '今日小单净流入-净额',
    `small_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '今日小单净流入-净占比（单位：%）',
    `period_type` VARCHAR(20) NOT NULL DEFAULT '今日' COMMENT '周期类型（今日/3日/5日/10日/20日）',
    `stat_date` DATE NOT NULL COMMENT '数据日期',
    
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code_date_period` (`symbol`, `stat_date`, `period_type`),
    KEY `idx_serial_number` (`serial_number`),
    KEY `idx_stat_date` (`stat_date`),
    KEY `idx_code` (`symbol`),
    KEY `idx_period_type` (`period_type`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='个股资金流向排行')

# 东方财富-数据中心--大盘资金流向
CREATE_MARKET_FUND_FLOW_DDL  = """
CREATE TABLE IF NOT EXISTS `market_fund_flow`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `trade_date` DATE NOT NULL COMMENT '交易日期',
    `sh_close` DECIMAL(10,3) DEFAULT NULL COMMENT '上证-收盘价',
    `sh_pct_change` DECIMAL(8,3) DEFAULT NULL COMMENT '上证-涨跌幅（单位：%）',
    `sz_close` DECIMAL(10,3) DEFAULT NULL COMMENT '深证-收盘价',
    `sz_pct_change` DECIMAL(8,3) DEFAULT NULL COMMENT '深证-涨跌幅（单位：%）',
    `main_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '主力净流入-净额',
    `main_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '主力净流入-净占比（单位：%）',
    `super_large_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '超大单净流入-净额',
    `super_large_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '超大单净流入-净占比（单位：%）',
    `large_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '大单净流入-净额',
    `large_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '大单净流入-净占比（单位：%）',
    `medium_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '中单净流入-净额',
    `medium_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '中单净流入-净占比（单位：%）',
    `small_net_inflow` DECIMAL(18,3) DEFAULT NULL COMMENT '小单净流入-净额',
    `small_net_inflow_pct` DECIMAL(8,3) DEFAULT NULL COMMENT '小单净流入-净占比（单位：%）',
    
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_trade_date` (`trade_date`),
    KEY `idx_trade_date` (`trade_date`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='大盘资金流向')

# 月度数据
CREATE_INVESTOR_MARKET_STATS_DDL = """
CREATE TABLE IF NOT EXISTS `investor_market_stats`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `stat_date` DATE NOT NULL COMMENT '数据日期（按月，存储为当月第一天）',
    `new_investor_count` DECIMAL(12,2) DEFAULT NULL COMMENT '新增投资者数量（万户）',
    `new_investor_mom` DECIMAL(8,2) DEFAULT NULL COMMENT '新增投资者环比（单位：%）',
    `new_investor_yoy` DECIMAL(8,2) DEFAULT NULL COMMENT '新增投资者同比（单位：%）',
    `total_investor_amount` DECIMAL(12,2) DEFAULT NULL COMMENT '期末投资者总量（万户）',
    `total_investor_a_share` DECIMAL(12,2) DEFAULT NULL COMMENT '期末投资者A股账户（万户）',
    `total_investor_b_share` DECIMAL(12,2) DEFAULT NULL COMMENT '期末投资者B股账户（万户）',
    `total_market_cap` DECIMAL(20,4) DEFAULT NULL COMMENT '沪深总市值（亿元）',
    `avg_market_cap_per_investor` DECIMAL(12,4) DEFAULT NULL COMMENT '沪深户均市值（万元/户）',
    `sh_index_close` DECIMAL(10,4) DEFAULT NULL COMMENT '上证指数收盘价',
    `sh_index_pct_change` DECIMAL(8,4) DEFAULT NULL COMMENT '上证指数涨跌幅（单位：%）',
    
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_stat_date` (`stat_date`),
    KEY `idx_stat_date` (`stat_date`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='月度数据')


# 千股千评数据
CREATE_STOCK_COMMENT_EM_DDL = """
CREATE TABLE IF NOT EXISTS `stock_comment_em`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `serial_number` INT NOT NULL COMMENT '序号',
    `symbol` VARCHAR(10) NOT NULL COMMENT '股票代码',
    `name` VARCHAR(50) NOT NULL COMMENT '股票名称',
    `latest_price` DECIMAL(10,3) DEFAULT NULL COMMENT '最新价',
    `change_percent` DECIMAL(8,3) DEFAULT NULL COMMENT '涨跌幅（单位：%）',
    `turnover_rate` DECIMAL(8,3) DEFAULT NULL COMMENT '换手率（单位：%）',
    `pe_ratio` DECIMAL(12,4) DEFAULT NULL COMMENT '市盈率',
    `main_cost` DECIMAL(10,3) DEFAULT NULL COMMENT '主力成本',
    `institution_participation` DECIMAL(8,3) DEFAULT NULL COMMENT '机构参与度（单位：%）',
    `composite_score` DECIMAL(8,3) DEFAULT NULL COMMENT '综合得分',
    `trend` INT DEFAULT NULL COMMENT '上升（正/负号表示趋势方向）',
    `current_rank` INT DEFAULT NULL COMMENT '目前排名',
    `attention_index` DECIMAL(8,3) DEFAULT NULL COMMENT '关注指数',
    `trade_date` DATE NOT NULL COMMENT '交易日（对应评级的日期）',
    
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_symbol_trade_date` (`symbol`, `trade_date`),
    KEY `idx_serial_number` (`serial_number`),
    KEY `idx_trade_date` (`trade_date`),
    KEY `idx_symbol` (`symbol`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='千股千评数据')

# 千股千评-市场参与意愿
CREATE_STOCK_COMMENT_DETAIL_EM_DDL = """
CREATE TABLE IF NOT EXISTS `stock_comment_detail_em`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `symbol` VARCHAR(10) NOT NULL COMMENT '股票代码',
    `name` VARCHAR(50) NOT NULL COMMENT '股票名称',
    `trade_date` DATE NOT NULL COMMENT '交易日期',
    `desire_value` DECIMAL(10, 4) DEFAULT NULL COMMENT '参与意愿',
    `avg_5_desire` DECIMAL(10, 4) DEFAULT NULL COMMENT '5日平均参与意愿',
    `desire_change` DECIMAL(10, 4) DEFAULT NULL COMMENT '参与意愿变化',
    `avg_5_change` DECIMAL(10, 4) DEFAULT NULL COMMENT '5日平均变化',
    `crawl_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '数据采集时间',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_symbol_date` (`symbol`, `trade_date`, `name`),
    KEY `idx_symbol` (`symbol`),
    KEY `idx_trade_date` (`trade_date`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='千股千评-市场参与意愿')


# 千股千评-市场参与意愿
CREATE_STOCK_HOLDER_NUM_DDL = """
CREATE TABLE IF NOT EXISTS `stock_holder_num`(
     `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `symbol` VARCHAR(10) NOT NULL COMMENT '股票代码',
    `name` VARCHAR(50) NOT NULL COMMENT '股票名称',
    `end_date` DATE NOT NULL COMMENT '股东户数统计截止日',
    `interval_pct_change` DECIMAL(12,4) DEFAULT NULL COMMENT '区间涨跌幅（单位：%）',
    `holder_num_current` BIGINT DEFAULT NULL COMMENT '股东户数-本次',
    `holder_num_previous` BIGINT DEFAULT NULL COMMENT '股东户数-上次',
    `holder_num_change` BIGINT DEFAULT NULL COMMENT '股东户数-增减',
    `holder_num_change_pct` DECIMAL(12,4) DEFAULT NULL COMMENT '股东户数-增减比例（单位：%）',
    `avg_market_cap_per_holder` DECIMAL(20,4) DEFAULT NULL COMMENT '户均持股市值（元）',
    `avg_share_per_holder` DECIMAL(20,4) DEFAULT NULL COMMENT '户均持股数量（股）',
    `total_market_cap` DECIMAL(20,4) DEFAULT NULL COMMENT '总市值（元）',
    `total_shares` BIGINT DEFAULT NULL COMMENT '总股本（股）',
    `share_change` BIGINT DEFAULT NULL COMMENT '股本变动（股）',
    `share_change_reason` VARCHAR(100) DEFAULT NULL COMMENT '股本变动原因',
    `announce_date` DATE DEFAULT NULL COMMENT '股东户数公告日期',
    
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_symbol_enddate` (`symbol`, `end_date`),
    KEY `idx_end_date` (`end_date`),
    KEY `idx_symbol` (`symbol`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='股东户数（东方财富）')


# ═══════════════════════════════════════════════════════════════════
#  个股资金流向表（stock_stock_flow）
# ═══════════════════════════════════════════════════════════════════

CREATE_STOCK_STOCK_FLOW_DDL = """
CREATE TABLE IF NOT EXISTS `stock_stock_flow` (
    `symbol`              VARCHAR(20)   NOT NULL                   COMMENT '股票代码',
    `name`                VARCHAR(100)  DEFAULT NULL               COMMENT '股票名称',
    `current_price`       DECIMAL(20,4) DEFAULT NULL               COMMENT '最新价',
    `change_percent`      DECIMAL(10,4) DEFAULT NULL               COMMENT '涨跌幅',
    `main_net_inflow`     DECIMAL(30,2) DEFAULT NULL               COMMENT '主力净流入',
    `main_net_inflow_pct` DECIMAL(10,4) DEFAULT NULL               COMMENT '主力净流入占比',
    `super_large_net_inflow`     DECIMAL(30,2) DEFAULT NULL        COMMENT '超大单净流入',
    `super_large_net_inflow_pct` DECIMAL(10,4) DEFAULT NULL        COMMENT '超大单净流入占比',
    `large_net_inflow`          DECIMAL(30,2) DEFAULT NULL        COMMENT '大单净流入',
    `large_net_inflow_pct`      DECIMAL(10,4) DEFAULT NULL        COMMENT '大单净流入占比',
    `medium_net_inflow`         DECIMAL(30,2) DEFAULT NULL        COMMENT '中单净流入',
    `medium_net_inflow_pct`     DECIMAL(10,4) DEFAULT NULL        COMMENT '中单净流入占比',
    `small_net_inflow`          DECIMAL(30,2) DEFAULT NULL        COMMENT '小单净流入',
    `small_net_inflow_pct`      DECIMAL(10,4) DEFAULT NULL        COMMENT '小单净流入占比',
    `stat_date`           DATE          NOT NULL DEFAULT '1970-01-01' COMMENT '统计日期',
    `period_type`         VARCHAR(20)   NOT NULL DEFAULT ''        COMMENT '周期类型(即时/3日排行/5日排行/10日排行/20日排行)',
    PRIMARY KEY (`symbol`, `stat_date`, `period_type`),
    INDEX idx_stat_date (`stat_date`),
    INDEX idx_period_type (`period_type`),
""" + TABLE_COMMON_SUFFIX.format(table_comment='个股资金流向')


# ═══════════════════════════════════════════════════════════════════
#  所有DDL语句集合
# ═══════════════════════════════════════════════════════════════════

ALL_FINANCIAL_DDL_STATEMENTS = [
    CREATE_FINANCIAL_BALANCE_SHEET_DDL,
    CREATE_FINANCIAL_INCOME_STATEMENT_DDL,
    CREATE_FINANCIAL_CASH_FLOW_DDL,
    CREATE_FINANCIAL_FORECAST_SUMMARY_DDL,
    CREATE_FINANCIAL_FORECAST_INSTITUTION_DDL,
    CREATE_FINANCIAL_INDICATOR_TREND_DDL,
    CREATE_STOCK_FUNDS_DDL,
    CREATE_INDUSTRY_FUNDS_INDIVIDUAL_DDL,
    CREATE_STOCK_INDIVIDUAL_FUND_FLOW_DDL,
    CREATE_STOCK_RANK_FUND_FLOW_DDL,
    CREATE_MARKET_FUND_FLOW_DDL,
    CREATE_INVESTOR_MARKET_STATS_DDL,
    CREATE_STOCK_COMMENT_EM_DDL,
    CREATE_STOCK_COMMENT_DETAIL_EM_DDL,
    CREATE_STOCK_HOLDER_NUM_DDL,
    CREATE_STOCK_STOCK_FLOW_DDL,
]