-- ================================================================
-- 量华平台 · 新闻数据库完整建表 DDL
-- 生成时间：2026-04-06
--
-- 数据库：news_data（独立库，密码 042018）
-- 所有新闻表统一建在 news_data 库下
-- 分表格式：news_{type}_{YYYYMM}（6种类型 × 每月1张）
-- 每张分表包含全部44个字段（基础+AI+情感+量化+治理），无需第二张同步表
-- 去重机制：url_hash (MD5) 唯一索引
--
-- 分表类型：
--   news_company_YYYYMM    公司动态新闻
--   news_cctv_YYYYMM       新闻联播
--   news_caixin_YYYYMM     财新新闻
--   news_global_YYYYMM     国际新闻
--   news_notice_YYYYMM     公告
--   news_stock_YYYYMM      个股新闻（研报）
-- ================================================================


-- ═══════════════════════════════════════════════════════════════════
-- 一、创建 news_data 数据库（如不存在）
-- ═══════════════════════════════════════════════════════════════════

CREATE DATABASE IF NOT EXISTS `news_data`
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE `news_data`;


-- ═══════════════════════════════════════════════════════════════════
-- 二、分表 DDL 模板（每张表包含全部44字段）
--     建表时替换 {table_name} 和 {comment} 即可
-- ═══════════════════════════════════════════════════════════════════

-- ── 2.1 公司动态新闻 ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `news_company_202604` (
    -- 基础信息（8字段）
    id                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    title               VARCHAR(500)   NOT NULL DEFAULT ''          COMMENT '标题',
    content             LONGTEXT       DEFAULT NULL                  COMMENT '正文',
    url                 VARCHAR(1000)  DEFAULT NULL                  COMMENT '原文链接',
    source              VARCHAR(100)   NOT NULL DEFAULT ''           COMMENT '来源',
    source_category     VARCHAR(50)    NOT NULL DEFAULT ''           COMMENT '来源分类: 东方财富/财联社/新闻联播/东方财富研报等',
    news_type           VARCHAR(20)    NOT NULL DEFAULT ''           COMMENT '分类: company/cctv/caixin/global/notice/stock',
    publish_time        DATETIME       DEFAULT NULL                  COMMENT '发布时间',
    collect_time        DATETIME       DEFAULT CURRENT_TIMESTAMP     COMMENT '入库时间',

    -- AI 分析（17字段）
    ai_interpretation     TEXT         DEFAULT NULL                  COMMENT 'AI解读',
    ai_event_type         VARCHAR(50)  DEFAULT NULL                  COMMENT '事件类型',
    ai_impact_level       TINYINT      DEFAULT NULL                  COMMENT 'AI评估影响等级(1=轻微,5=重大)',
    ai_impact_direction   TINYINT      DEFAULT NULL                  COMMENT '影响方向(1=利好,0=中性,-1=利空)',
    ai_impact_duration    VARCHAR(20)  DEFAULT NULL                  COMMENT '影响持续时间(短期/中期/长期)',
    ai_risk_level         TINYINT      DEFAULT NULL                  COMMENT '风险等级(1=低风险,5=高风险)',
    ai_benefit_sectors    TEXT         DEFAULT NULL                  COMMENT 'AI受益板块',
    ai_benefit_stocks     TEXT         DEFAULT NULL                  COMMENT 'AI受益个股',
    ai_key_suppliers      TEXT         DEFAULT NULL                  COMMENT 'AI关键供应商',
    ai_keywords           TEXT         DEFAULT NULL                  COMMENT '核心关键词(逗号分隔)',
    ai_topic_tags         TEXT         DEFAULT NULL                  COMMENT '主题标签(逗号分隔)',
    ai_related_indices    TEXT         DEFAULT NULL                  COMMENT '关联指数(逗号分隔)',
    ai_analyze_time       DATETIME     DEFAULT NULL                  COMMENT 'AI分析完成时间',
    need_analyze          TINYINT      DEFAULT 1                     COMMENT '是否需要AI分析(1=是,0=否)',
    source_level          TINYINT      DEFAULT 3                     COMMENT '来源可信度等级(1=最高,5=最低)',
    is_official           TINYINT      DEFAULT 0                     COMMENT '是否官方公告(1=是,0=否)',
    is_breaking           TINYINT      DEFAULT 0                     COMMENT '是否突发新闻(1=是,0=否)',

    -- 情感分析（8字段）
    sentiment             FLOAT        DEFAULT NULL                  COMMENT '全文情感得分',
    title_sentiment       FLOAT        DEFAULT NULL                  COMMENT '标题情感得分',
    sentiment_label       TINYINT      DEFAULT NULL                  COMMENT '情感标签: 1=正面,0=中性,-1=负面',
    title_sentiment_label TINYINT      DEFAULT NULL                  COMMENT '标题情感标签',
    sentiment_confidence  FLOAT        DEFAULT NULL                  COMMENT '情感置信度',
    sentiment_volatility  FLOAT        DEFAULT NULL                  COMMENT '情感波动度',
    subjectivity_score    FLOAT        DEFAULT NULL                  COMMENT '主观性得分(0=客观,1=主观)',
    emotion_type          VARCHAR(20)  DEFAULT NULL                  COMMENT '情绪类型',

    -- 量化交易适配（6字段）
    is_processed          TINYINT      DEFAULT 0                     COMMENT '是否已被策略处理(1=是,0=否)',
    strategy_signal       TINYINT      DEFAULT NULL                  COMMENT '策略信号(1=买入,0=持有,-1=卖出)',
    signal_strength       FLOAT        DEFAULT NULL                  COMMENT '信号强度(0-1)',
    signal_expire_time    DATETIME     DEFAULT NULL                  COMMENT '信号失效时间',
    backtest_result       TEXT         DEFAULT NULL                  COMMENT '回测结果(JSON)',
    market_reaction       TEXT         DEFAULT NULL                  COMMENT '市场实际反应(JSON)',

    -- 数据治理（5字段）
    create_time           DATETIME     DEFAULT CURRENT_TIMESTAMP     COMMENT '记录创建时间',
    update_time           DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    data_version          VARCHAR(20)  DEFAULT 'v1.0'                COMMENT '数据版本号',
    operator              VARCHAR(50)  DEFAULT NULL                  COMMENT '操作人/系统',
    is_deleted            TINYINT      DEFAULT 0                     COMMENT '逻辑删除(1=删除,0=正常)',

    -- 去重 & 索引
    url_hash              CHAR(32)     DEFAULT NULL                  COMMENT 'URL MD5摘要(去重)',
    INDEX idx_publish_time        (publish_time),
    INDEX idx_collect_time        (collect_time),
    INDEX idx_source_category     (source_category),
    INDEX idx_need_analyze        (need_analyze),
    INDEX idx_is_processed        (is_processed),
    INDEX idx_ai_impact_direction (ai_impact_direction),
    INDEX idx_is_deleted          (is_deleted),
    INDEX idx_news_type           (news_type),
    INDEX idx_source              (source),
    UNIQUE INDEX uk_url_hash      (url_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公司动态新闻';

-- ── 2.2 新闻联播 ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `news_cctv_202604` (
    id                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    title               VARCHAR(500)   NOT NULL DEFAULT '',
    content             LONGTEXT       DEFAULT NULL,
    url                 VARCHAR(1000)  DEFAULT NULL,
    source              VARCHAR(100)   NOT NULL DEFAULT '',
    source_category     VARCHAR(50)    NOT NULL DEFAULT '',
    news_type           VARCHAR(20)    NOT NULL DEFAULT '',
    publish_time        DATETIME       DEFAULT NULL,
    collect_time        DATETIME       DEFAULT CURRENT_TIMESTAMP,
    ai_interpretation     TEXT         DEFAULT NULL,
    ai_event_type         VARCHAR(50)  DEFAULT NULL,
    ai_impact_level       TINYINT      DEFAULT NULL,
    ai_impact_direction   TINYINT      DEFAULT NULL,
    ai_impact_duration    VARCHAR(20)  DEFAULT NULL,
    ai_risk_level         TINYINT      DEFAULT NULL,
    ai_benefit_sectors    TEXT         DEFAULT NULL,
    ai_benefit_stocks     TEXT         DEFAULT NULL,
    ai_key_suppliers      TEXT         DEFAULT NULL,
    ai_keywords           TEXT         DEFAULT NULL,
    ai_topic_tags         TEXT         DEFAULT NULL,
    ai_related_indices    TEXT         DEFAULT NULL,
    ai_analyze_time       DATETIME     DEFAULT NULL,
    need_analyze          TINYINT      DEFAULT 1,
    source_level          TINYINT      DEFAULT 3,
    is_official           TINYINT      DEFAULT 0,
    is_breaking           TINYINT      DEFAULT 0,
    sentiment             FLOAT        DEFAULT NULL,
    title_sentiment       FLOAT        DEFAULT NULL,
    sentiment_label       TINYINT      DEFAULT NULL,
    title_sentiment_label TINYINT      DEFAULT NULL,
    sentiment_confidence  FLOAT        DEFAULT NULL,
    sentiment_volatility  FLOAT        DEFAULT NULL,
    subjectivity_score    FLOAT        DEFAULT NULL,
    emotion_type          VARCHAR(20)  DEFAULT NULL,
    is_processed          TINYINT      DEFAULT 0,
    strategy_signal       TINYINT      DEFAULT NULL,
    signal_strength       FLOAT        DEFAULT NULL,
    signal_expire_time    DATETIME     DEFAULT NULL,
    backtest_result       TEXT         DEFAULT NULL,
    market_reaction       TEXT         DEFAULT NULL,
    create_time           DATETIME     DEFAULT CURRENT_TIMESTAMP,
    update_time           DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    data_version          VARCHAR(20)  DEFAULT 'v1.0',
    operator              VARCHAR(50)  DEFAULT NULL,
    is_deleted            TINYINT      DEFAULT 0,
    url_hash              CHAR(32)     DEFAULT NULL,
    INDEX idx_publish_time        (publish_time),
    INDEX idx_collect_time        (collect_time),
    INDEX idx_source_category     (source_category),
    INDEX idx_need_analyze        (need_analyze),
    INDEX idx_is_processed        (is_processed),
    INDEX idx_ai_impact_direction (ai_impact_direction),
    INDEX idx_is_deleted          (is_deleted),
    INDEX idx_news_type           (news_type),
    INDEX idx_source              (source),
    UNIQUE INDEX uk_url_hash      (url_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='新闻联播';

-- ── 2.3 财新新闻 ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `news_caixin_202604` (
    id                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    title               VARCHAR(500)   NOT NULL DEFAULT '',
    content             LONGTEXT       DEFAULT NULL,
    url                 VARCHAR(1000)  DEFAULT NULL,
    source              VARCHAR(100)   NOT NULL DEFAULT '',
    source_category     VARCHAR(50)    NOT NULL DEFAULT '',
    news_type           VARCHAR(20)    NOT NULL DEFAULT '',
    publish_time        DATETIME       DEFAULT NULL,
    collect_time        DATETIME       DEFAULT CURRENT_TIMESTAMP,
    ai_interpretation     TEXT         DEFAULT NULL,
    ai_event_type         VARCHAR(50)  DEFAULT NULL,
    ai_impact_level       TINYINT      DEFAULT NULL,
    ai_impact_direction   TINYINT      DEFAULT NULL,
    ai_impact_duration    VARCHAR(20)  DEFAULT NULL,
    ai_risk_level         TINYINT      DEFAULT NULL,
    ai_benefit_sectors    TEXT         DEFAULT NULL,
    ai_benefit_stocks     TEXT         DEFAULT NULL,
    ai_key_suppliers      TEXT         DEFAULT NULL,
    ai_keywords           TEXT         DEFAULT NULL,
    ai_topic_tags         TEXT         DEFAULT NULL,
    ai_related_indices    TEXT         DEFAULT NULL,
    ai_analyze_time       DATETIME     DEFAULT NULL,
    need_analyze          TINYINT      DEFAULT 1,
    source_level          TINYINT      DEFAULT 3,
    is_official           TINYINT      DEFAULT 0,
    is_breaking           TINYINT      DEFAULT 0,
    sentiment             FLOAT        DEFAULT NULL,
    title_sentiment       FLOAT        DEFAULT NULL,
    sentiment_label       TINYINT      DEFAULT NULL,
    title_sentiment_label TINYINT      DEFAULT NULL,
    sentiment_confidence  FLOAT        DEFAULT NULL,
    sentiment_volatility  FLOAT        DEFAULT NULL,
    subjectivity_score    FLOAT        DEFAULT NULL,
    emotion_type          VARCHAR(20)  DEFAULT NULL,
    is_processed          TINYINT      DEFAULT 0,
    strategy_signal       TINYINT      DEFAULT NULL,
    signal_strength       FLOAT        DEFAULT NULL,
    signal_expire_time    DATETIME     DEFAULT NULL,
    backtest_result       TEXT         DEFAULT NULL,
    market_reaction       TEXT         DEFAULT NULL,
    create_time           DATETIME     DEFAULT CURRENT_TIMESTAMP,
    update_time           DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    data_version          VARCHAR(20)  DEFAULT 'v1.0',
    operator              VARCHAR(50)  DEFAULT NULL,
    is_deleted            TINYINT      DEFAULT 0,
    url_hash              CHAR(32)     DEFAULT NULL,
    INDEX idx_publish_time        (publish_time),
    INDEX idx_collect_time        (collect_time),
    INDEX idx_source_category     (source_category),
    INDEX idx_need_analyze        (need_analyze),
    INDEX idx_is_processed        (is_processed),
    INDEX idx_ai_impact_direction (ai_impact_direction),
    INDEX idx_is_deleted          (is_deleted),
    INDEX idx_news_type           (news_type),
    INDEX idx_source              (source),
    UNIQUE INDEX uk_url_hash      (url_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='财新新闻';

-- ── 2.4 国际新闻 ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `news_global_202604` (
    id                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    title               VARCHAR(500)   NOT NULL DEFAULT '',
    content             LONGTEXT       DEFAULT NULL,
    url                 VARCHAR(1000)  DEFAULT NULL,
    source              VARCHAR(100)   NOT NULL DEFAULT '',
    source_category     VARCHAR(50)    NOT NULL DEFAULT '',
    news_type           VARCHAR(20)    NOT NULL DEFAULT '',
    publish_time        DATETIME       DEFAULT NULL,
    collect_time        DATETIME       DEFAULT CURRENT_TIMESTAMP,
    ai_interpretation     TEXT         DEFAULT NULL,
    ai_event_type         VARCHAR(50)  DEFAULT NULL,
    ai_impact_level       TINYINT      DEFAULT NULL,
    ai_impact_direction   TINYINT      DEFAULT NULL,
    ai_impact_duration    VARCHAR(20)  DEFAULT NULL,
    ai_risk_level         TINYINT      DEFAULT NULL,
    ai_benefit_sectors    TEXT         DEFAULT NULL,
    ai_benefit_stocks     TEXT         DEFAULT NULL,
    ai_key_suppliers      TEXT         DEFAULT NULL,
    ai_keywords           TEXT         DEFAULT NULL,
    ai_topic_tags         TEXT         DEFAULT NULL,
    ai_related_indices    TEXT         DEFAULT NULL,
    ai_analyze_time       DATETIME     DEFAULT NULL,
    need_analyze          TINYINT      DEFAULT 1,
    source_level          TINYINT      DEFAULT 3,
    is_official           TINYINT      DEFAULT 0,
    is_breaking           TINYINT      DEFAULT 0,
    sentiment             FLOAT        DEFAULT NULL,
    title_sentiment       FLOAT        DEFAULT NULL,
    sentiment_label       TINYINT      DEFAULT NULL,
    title_sentiment_label TINYINT      DEFAULT NULL,
    sentiment_confidence  FLOAT        DEFAULT NULL,
    sentiment_volatility  FLOAT        DEFAULT NULL,
    subjectivity_score    FLOAT        DEFAULT NULL,
    emotion_type          VARCHAR(20)  DEFAULT NULL,
    is_processed          TINYINT      DEFAULT 0,
    strategy_signal       TINYINT      DEFAULT NULL,
    signal_strength       FLOAT        DEFAULT NULL,
    signal_expire_time    DATETIME     DEFAULT NULL,
    backtest_result       TEXT         DEFAULT NULL,
    market_reaction       TEXT         DEFAULT NULL,
    create_time           DATETIME     DEFAULT CURRENT_TIMESTAMP,
    update_time           DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    data_version          VARCHAR(20)  DEFAULT 'v1.0',
    operator              VARCHAR(50)  DEFAULT NULL,
    is_deleted            TINYINT      DEFAULT 0,
    url_hash              CHAR(32)     DEFAULT NULL,
    INDEX idx_publish_time        (publish_time),
    INDEX idx_collect_time        (collect_time),
    INDEX idx_source_category     (source_category),
    INDEX idx_need_analyze        (need_analyze),
    INDEX idx_is_processed        (is_processed),
    INDEX idx_ai_impact_direction (ai_impact_direction),
    INDEX idx_is_deleted          (is_deleted),
    INDEX idx_news_type           (news_type),
    INDEX idx_source              (source),
    UNIQUE INDEX uk_url_hash      (url_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='国际新闻';

-- ── 2.5 公告 ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `news_notice_202604` (
    id                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    title               VARCHAR(500)   NOT NULL DEFAULT '',
    content             LONGTEXT       DEFAULT NULL,
    url                 VARCHAR(1000)  DEFAULT NULL,
    source              VARCHAR(100)   NOT NULL DEFAULT '',
    source_category     VARCHAR(50)    NOT NULL DEFAULT '',
    news_type           VARCHAR(20)    NOT NULL DEFAULT '',
    publish_time        DATETIME       DEFAULT NULL,
    collect_time        DATETIME       DEFAULT CURRENT_TIMESTAMP,
    ai_interpretation     TEXT         DEFAULT NULL,
    ai_event_type         VARCHAR(50)  DEFAULT NULL,
    ai_impact_level       TINYINT      DEFAULT NULL,
    ai_impact_direction   TINYINT      DEFAULT NULL,
    ai_impact_duration    VARCHAR(20)  DEFAULT NULL,
    ai_risk_level         TINYINT      DEFAULT NULL,
    ai_benefit_sectors    TEXT         DEFAULT NULL,
    ai_benefit_stocks     TEXT         DEFAULT NULL,
    ai_key_suppliers      TEXT         DEFAULT NULL,
    ai_keywords           TEXT         DEFAULT NULL,
    ai_topic_tags         TEXT         DEFAULT NULL,
    ai_related_indices    TEXT         DEFAULT NULL,
    ai_analyze_time       DATETIME     DEFAULT NULL,
    need_analyze          TINYINT      DEFAULT 1,
    source_level          TINYINT      DEFAULT 3,
    is_official           TINYINT      DEFAULT 0,
    is_breaking           TINYINT      DEFAULT 0,
    sentiment             FLOAT        DEFAULT NULL,
    title_sentiment       FLOAT        DEFAULT NULL,
    sentiment_label       TINYINT      DEFAULT NULL,
    title_sentiment_label TINYINT      DEFAULT NULL,
    sentiment_confidence  FLOAT        DEFAULT NULL,
    sentiment_volatility  FLOAT        DEFAULT NULL,
    subjectivity_score    FLOAT        DEFAULT NULL,
    emotion_type          VARCHAR(20)  DEFAULT NULL,
    is_processed          TINYINT      DEFAULT 0,
    strategy_signal       TINYINT      DEFAULT NULL,
    signal_strength       FLOAT        DEFAULT NULL,
    signal_expire_time    DATETIME     DEFAULT NULL,
    backtest_result       TEXT         DEFAULT NULL,
    market_reaction       TEXT         DEFAULT NULL,
    create_time           DATETIME     DEFAULT CURRENT_TIMESTAMP,
    update_time           DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    data_version          VARCHAR(20)  DEFAULT 'v1.0',
    operator              VARCHAR(50)  DEFAULT NULL,
    is_deleted            TINYINT      DEFAULT 0,
    url_hash              CHAR(32)     DEFAULT NULL,
    INDEX idx_publish_time        (publish_time),
    INDEX idx_collect_time        (collect_time),
    INDEX idx_source_category     (source_category),
    INDEX idx_need_analyze        (need_analyze),
    INDEX idx_is_processed        (is_processed),
    INDEX idx_ai_impact_direction (ai_impact_direction),
    INDEX idx_is_deleted          (is_deleted),
    INDEX idx_news_type           (news_type),
    INDEX idx_source              (source),
    UNIQUE INDEX uk_url_hash      (url_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公告';

-- ── 2.6 个股新闻（研报）────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `news_stock_202604` (
    id                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    title               VARCHAR(500)   NOT NULL DEFAULT '',
    content             LONGTEXT       DEFAULT NULL,
    url                 VARCHAR(1000)  DEFAULT NULL,
    source              VARCHAR(100)   NOT NULL DEFAULT '',
    source_category     VARCHAR(50)    NOT NULL DEFAULT '',
    news_type           VARCHAR(20)    NOT NULL DEFAULT '',
    publish_time        DATETIME       DEFAULT NULL,
    collect_time        DATETIME       DEFAULT CURRENT_TIMESTAMP,
    ai_interpretation     TEXT         DEFAULT NULL,
    ai_event_type         VARCHAR(50)  DEFAULT NULL,
    ai_impact_level       TINYINT      DEFAULT NULL,
    ai_impact_direction   TINYINT      DEFAULT NULL,
    ai_impact_duration    VARCHAR(20)  DEFAULT NULL,
    ai_risk_level         TINYINT      DEFAULT NULL,
    ai_benefit_sectors    TEXT         DEFAULT NULL,
    ai_benefit_stocks     TEXT         DEFAULT NULL,
    ai_key_suppliers      TEXT         DEFAULT NULL,
    ai_keywords           TEXT         DEFAULT NULL,
    ai_topic_tags         TEXT         DEFAULT NULL,
    ai_related_indices    TEXT         DEFAULT NULL,
    ai_analyze_time       DATETIME     DEFAULT NULL,
    need_analyze          TINYINT      DEFAULT 1,
    source_level          TINYINT      DEFAULT 3,
    is_official           TINYINT      DEFAULT 0,
    is_breaking           TINYINT      DEFAULT 0,
    sentiment             FLOAT        DEFAULT NULL,
    title_sentiment       FLOAT        DEFAULT NULL,
    sentiment_label       TINYINT      DEFAULT NULL,
    title_sentiment_label TINYINT      DEFAULT NULL,
    sentiment_confidence  FLOAT        DEFAULT NULL,
    sentiment_volatility  FLOAT        DEFAULT NULL,
    subjectivity_score    FLOAT        DEFAULT NULL,
    emotion_type          VARCHAR(20)  DEFAULT NULL,
    is_processed          TINYINT      DEFAULT 0,
    strategy_signal       TINYINT      DEFAULT NULL,
    signal_strength       FLOAT        DEFAULT NULL,
    signal_expire_time    DATETIME     DEFAULT NULL,
    backtest_result       TEXT         DEFAULT NULL,
    market_reaction       TEXT         DEFAULT NULL,
    create_time           DATETIME     DEFAULT CURRENT_TIMESTAMP,
    update_time           DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    data_version          VARCHAR(20)  DEFAULT 'v1.0',
    operator              VARCHAR(50)  DEFAULT NULL,
    is_deleted            TINYINT      DEFAULT 0,
    url_hash              CHAR(32)     DEFAULT NULL,
    INDEX idx_publish_time        (publish_time),
    INDEX idx_collect_time        (collect_time),
    INDEX idx_source_category     (source_category),
    INDEX idx_need_analyze        (need_analyze),
    INDEX idx_is_processed        (is_processed),
    INDEX idx_ai_impact_direction (ai_impact_direction),
    INDEX idx_is_deleted          (is_deleted),
    INDEX idx_news_type           (news_type),
    INDEX idx_source              (source),
    UNIQUE INDEX uk_url_hash      (url_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='个股新闻（研报）';
